---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    name: nginx
spec:
  type: LoadBalancer
  ports:
    - port: 80
      nodePort: 30881
      name: http
    - port: 443
      nodePort: 31443
      name: https
  selector:
    name: nginx
